import type { InsertListing } from "@shared/schema";

const defaultLeaseOptions = [
  { months: 1, label: "Short Stay" },
  { months: 4, label: "Semester" },
  { months: 6, label: "Half-Year" },
  { months: 12, label: "Annual" },
];

export const seedListings: InsertListing[] = [
  {
    ownerUserId: "owner-sabai-living",
    universityId: "rsu",
    title: "Plum Condo Park Rangsit",
    location: "Klong Nueng, Pathum Thani",
    price: 8500,
    rating: "4.80",
    category: "CONDO",
    roomType: "condo",
    image: "/images/condo-exterior.png",
    gallery: [
      "/images/condo-exterior.png",
      "/images/condo-interior.png",
      "/images/condo-pool.png",
    ],
    description:
      "Modern student living near RSU with secure access, strong study amenities, and a straightforward semester leasing flow.",
    latitude: "13.9612000",
    longitude: "100.6015000",
    areaSqm: 28,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: true,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: [
      "Pool",
      "Gym",
      "24/7 Security",
      "Study Lounge",
      "Laundry",
      "Air Conditioning",
    ],
    nearestCampusZoneId: "rsu-main-gate",
    walkingMinutes: 11,
    transportRouteIds: ["rsu-shuttle-green", "songthaew-muang-ake"],
    utilityRates: {
      electricityPerUnit: 7,
      waterPerUnit: 20,
      internetFee: 0,
      serviceFee: 350,
    },
    internetIncluded: true,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-05-01"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-kave",
    universityId: "rsu",
    title: "Kave Town Space",
    location: "Chiang Rak, Near TU/RSU",
    price: 12000,
    rating: "4.90",
    category: "LUXURY",
    roomType: "studio",
    image: "/images/condo-interior.png",
    gallery: [
      "/images/condo-interior.png",
      "/images/co-working.png",
      "/images/condo-pool.png",
    ],
    description:
      "Premium studio inventory with smart locks, co-working access, and fast owner response times for international and local students.",
    latitude: "13.9680000",
    longitude: "100.6050000",
    areaSqm: 32,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: true,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: [
      "Co-working",
      "Rooftop",
      "Fiber Internet",
      "Smart Lock",
      "Fitness Center",
    ],
    nearestCampusZoneId: "rsu-library",
    walkingMinutes: 14,
    transportRouteIds: ["rsu-shuttle-green"],
    utilityRates: {
      electricityPerUnit: 8,
      waterPerUnit: 18,
      internetFee: 0,
      serviceFee: 500,
    },
    internetIncluded: true,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-05-15"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-dcondo",
    universityId: "rsu",
    title: "Dcondo Campus Resort",
    location: "Rangsit-Pathum Thani",
    price: 9500,
    rating: "4.70",
    category: "RESORT",
    roomType: "apartment",
    image: "/images/condo-pool.png",
    gallery: [
      "/images/condo-pool.png",
      "/images/condo-exterior.png",
      "/images/condo-interior.png",
    ],
    description:
      "Resort-style student apartments with shuttle support, pool access, and stable utility pricing for semester stays.",
    latitude: "13.9720000",
    longitude: "100.5980000",
    areaSqm: 30,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: false,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: ["Pool", "Garden", "Study Pods", "Laundry", "Shuttle Pickup"],
    nearestCampusZoneId: "rsu-engineering",
    walkingMinutes: 18,
    transportRouteIds: ["rsu-shuttle-green"],
    utilityRates: {
      electricityPerUnit: 6,
      waterPerUnit: 17,
      internetFee: 450,
      serviceFee: 300,
    },
    internetIncluded: false,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-04-20"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-loft",
    universityId: "rsu",
    title: "The Sky Loft RSU",
    location: "Lak Hok, Rangsit",
    price: 15000,
    rating: "4.95",
    category: "LOFT",
    roomType: "loft",
    image: "/images/co-working.png",
    gallery: ["/images/co-working.png", "/images/condo-interior.png"],
    description:
      "Creative loft inventory with double-height living space, studio-friendly layout, and premium owner-managed contracts.",
    latitude: "13.9630000",
    longitude: "100.5890000",
    areaSqm: 42,
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1.5,
    featured: true,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: ["Creative Studio", "Meeting Room", "Coffee Bar", "Security"],
    nearestCampusZoneId: "rsu-design",
    walkingMinutes: 7,
    transportRouteIds: ["songthaew-muang-ake"],
    utilityRates: {
      electricityPerUnit: 8,
      waterPerUnit: 20,
      internetFee: 600,
      serviceFee: 500,
    },
    internetIncluded: false,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-06-01"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-attitude",
    universityId: "rsu",
    title: "Attitude Bu Condo",
    location: "Phahonyothin Rd",
    price: 11000,
    rating: "4.85",
    category: "CREATIVE",
    roomType: "studio",
    image: "/images/condo-exterior.png",
    gallery: ["/images/condo-exterior.png", "/images/co-working.png"],
    description:
      "Color-forward condo community with social lounges, rooftop study sessions, and flexible short-stay inventory for visiting families.",
    latitude: "13.9800000",
    longitude: "100.6100000",
    areaSqm: 31,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: false,
    listingStatus: "draft",
    moderationStatus: "pending",
    amenities: ["Rooftop Garden", "Study Lounge", "Cafe", "Laundry"],
    nearestCampusZoneId: "rsu-main-gate",
    walkingMinutes: 20,
    transportRouteIds: ["rsu-shuttle-green"],
    utilityRates: {
      electricityPerUnit: 7,
      waterPerUnit: 18,
      internetFee: 350,
      serviceFee: 280,
    },
    internetIncluded: false,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-05-10"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-common",
    universityId: "rsu",
    title: "Common TU",
    location: "Klong Luang",
    price: 13500,
    rating: "4.88",
    category: "LUXURY",
    roomType: "condo",
    image: "/images/condo-interior.png",
    gallery: ["/images/condo-interior.png", "/images/condo-pool.png"],
    description:
      "High-rise condo stock with premium common areas and structured admin-ready documents for contract approvals.",
    latitude: "13.9900000",
    longitude: "100.6000000",
    areaSqm: 35,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: false,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: ["Infinity Pool", "Reading Room", "Gym", "Lobby Concierge"],
    nearestCampusZoneId: "rsu-library",
    walkingMinutes: 16,
    transportRouteIds: ["rsu-shuttle-green"],
    utilityRates: {
      electricityPerUnit: 7,
      waterPerUnit: 19,
      internetFee: 0,
      serviceFee: 550,
    },
    internetIncluded: true,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-05-01"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-becondo",
    universityId: "rsu",
    title: "Be Condo Phaholyothin",
    location: "Near Rangsit University",
    price: 7500,
    rating: "4.60",
    category: "BUDGET",
    roomType: "studio",
    image: "/images/condo-interior.png",
    gallery: ["/images/condo-interior.png"],
    description:
      "Budget-conscious studio units with straightforward semester contracts and practical student-focused amenities.",
    latitude: "13.9660000",
    longitude: "100.5920000",
    areaSqm: 24,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: false,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: ["Laundry", "Security", "Mini Mart"],
    nearestCampusZoneId: "rsu-main-gate",
    walkingMinutes: 9,
    transportRouteIds: ["songthaew-muang-ake"],
    utilityRates: {
      electricityPerUnit: 6,
      waterPerUnit: 16,
      internetFee: 300,
      serviceFee: 180,
    },
    internetIncluded: false,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-04-15"),
    availableTo: null,
  },
  {
    ownerUserId: "owner-urban-cube",
    universityId: "rsu",
    title: "Urban Cube Dorm",
    location: "Muang Ake",
    price: 6000,
    rating: "4.50",
    category: "DORM",
    roomType: "dorm",
    image: "/images/co-working.png",
    gallery: ["/images/co-working.png", "/images/condo-exterior.png"],
    description:
      "Social dorm inventory in Muang Ake with shared kitchens, roommate-friendly policies, and excellent café access.",
    latitude: "13.9640000",
    longitude: "100.5860000",
    areaSqm: 22,
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    featured: false,
    listingStatus: "active",
    moderationStatus: "approved",
    amenities: ["Shared Kitchen", "Gaming Room", "Cafe Strip", "Laundry"],
    nearestCampusZoneId: "rsu-main-gate",
    walkingMinutes: 6,
    transportRouteIds: ["songthaew-muang-ake"],
    utilityRates: {
      electricityPerUnit: 5,
      waterPerUnit: 15,
      internetFee: 250,
      serviceFee: 150,
    },
    internetIncluded: false,
    leaseOptions: defaultLeaseOptions,
    availableFrom: new Date("2026-04-10"),
    availableTo: null,
  },
];
