-- Generated from https://www.renthub.in.th/en/apartment/rangsit-university
-- Generated at 2026-04-03T07:06:06.185Z
-- This script does NOT modify schema.sql and is safe to re-run.

do $$
declare
  rsu_university_id uuid;
  demo_owner_id uuid;
begin
  select id
  into rsu_university_id
  from public.universities
  where lower(email_domain) = 'rsu.ac.th'
  limit 1;

  if rsu_university_id is null then
    raise exception 'Rangsit University (rsu.ac.th) not found. Run schema.sql first.';
  end if;

  select id
  into demo_owner_id
  from public.app_users
  where role = 'owner'
  order by created_at
  limit 1;

  if demo_owner_id is null then
    select id
    into demo_owner_id
    from public.app_users
    order by created_at
    limit 1;

    if demo_owner_id is not null then
      update public.app_users
      set role = 'owner',
          full_name = coalesce(nullif(full_name, ''), 'RentHub Demo Owner'),
          updated_at = now()
      where id = demo_owner_id;
    end if;
  end if;

  if demo_owner_id is not null then
    insert into public.owner_profiles (user_id, business_name, verification_status, verified_at)
    values (demo_owner_id, 'RentHub Demo Owner', 'verified', now())
    on conflict (user_id) do update
      set business_name = excluded.business_name,
          verification_status = 'verified',
          verified_at = coalesce(owner_profiles.verified_at, excluded.verified_at),
          updated_at = now();
  else
    raise notice 'No app_users found; listings will be inserted with null owner_user_id.';
  end if;

  insert into public.listings (
    id,
    owner_user_id,
    university_id,
    title,
    location,
    price,
    rating,
    category,
    room_type,
    image,
    gallery,
    description,
    latitude,
    longitude,
    area_sqm,
    capacity,
    bedrooms,
    bathrooms,
    featured,
    listing_status,
    moderation_status,
    amenities,
    nearest_campus_zone_id,
    walking_minutes,
    transport_route_ids,
    utility_rates,
    internet_included,
    lease_options,
    available_from,
    available_to
  )
  values
(
      '00000000-0000-0000-0000-000000039833'::uuid,
      demo_owner_id,
      rsu_university_id,
      'THA THA APARTMENT',
      'Prachathipat, Thanyaburi, Pathumthani',
      2750,
      4.7,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201709/20170919/xENfcLjBnutYv24bxaXa.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201709/20170919/xENfcLjBnutYv24bxaXa.jpg"]'::jsonb,
      'Imported from RentHub listing #39833 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9966831,
      100.5563533,
      23,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Convenience Shop","Keycard Access"]'::jsonb,
      'rsu-library',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000063451'::uuid,
      demo_owner_id,
      rsu_university_id,
      'PremAnun Apartment',
      'Khu Khot, Lam Luk Ka, Pathumthani',
      4150,
      4.7,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202206/20220614/CTwzn7wgV3QLmGLcdAZD.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202206/20220614/CTwzn7wgV3QLmGLcdAZD.jpg"]'::jsonb,
      'Imported from RentHub listing #63451 near Rangsit University. Approx. 42 minutes to campus context. Address document verified on source platform.',
      13.9799468,
      100.6147729,
      25,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-design',
      42,
      '["songthaew-muang-ake","rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000042197'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Clifton House',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      9750,
      4.5,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201802/20180206/EUmnJeny53VCLTpyyED1.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201802/20180206/EUmnJeny53VCLTpyyED1.jpg"]'::jsonb,
      'Imported from RentHub listing #42197 near Rangsit University. Approx. 7 minutes to campus context. Address document verified on source platform.',
      13.9675895,
      100.5838531,
      34,
      2,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Laundry","Lift","Convenience Shop","Water Heater","Refrigerator","Fingerprint Access"]'::jsonb,
      'rsu-library',
      7,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":500,"serviceFee":250}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000069835'::uuid,
      demo_owner_id,
      rsu_university_id,
      'The Rise 789',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      8750,
      4.7,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202602/20260206/AF8mcRrkSoqrcvMyKazJ.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202602/20260206/AF8mcRrkSoqrcvMyKazJ.jpg"]'::jsonb,
      'Imported from RentHub listing #69835 near Rangsit University. Approx. 7 minutes to campus context. Address document verified on source platform.',
      13.9619267,
      100.583992,
      33,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Water Heater","Refrigerator","Keycard Access","Fingerprint Access"]'::jsonb,
      'rsu-design',
      7,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":0,"serviceFee":250}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000064936'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Parichart Apartment',
      'Bang Phun, Muang Pathum Thani, Pathumthani',
      3000,
      4.8,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202410/20241014/7zNWM7F5qUGpFAEHBmyT.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202410/20241014/7zNWM7F5qUGpFAEHBmyT.jpg"]'::jsonb,
      'Imported from RentHub listing #64936 near Rangsit University. Approx. 31 minutes to campus context. Address document verified on source platform.',
      13.9481197,
      100.6025745,
      23,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Laundry","Lift","Convenience Shop","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-main-gate',
      31,
      '["songthaew-muang-ake","rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":250,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000042714'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Le Fortune Place',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      7500,
      4.4,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202302/20230202/kuahBNCWnv5QmgxRLz4W.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202302/20230202/kuahBNCWnv5QmgxRLz4W.jpg"]'::jsonb,
      'Imported from RentHub listing #42714 near Rangsit University. Approx. 9 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9621259,
      100.5934807,
      31,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Water Heater","Refrigerator","Fingerprint Access"]'::jsonb,
      'rsu-engineering',
      9,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":350,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000024881'::uuid,
      demo_owner_id,
      rsu_university_id,
      'ART GARDEN HOSTEL',
      'Khu Khot, Lam Luk Ka, Pathumthani',
      3400,
      4.7,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202011/20201119/iBwfsv3M3LY299wT9VUY.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202011/20201119/iBwfsv3M3LY299wT9VUY.jpg"]'::jsonb,
      'Imported from RentHub listing #24881 near Rangsit University. Approx. 60 minutes to campus context. Address document verified on source platform.',
      13.9535171,
      100.538762,
      24,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-library',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000040700'::uuid,
      demo_owner_id,
      rsu_university_id,
      'B-yourhome',
      'Si Khan, Don Mueang, Bangkok',
      5250,
      4.6,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201711/20171110/bVWY3C1Jrx7pJ7hAJZZK.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201711/20171110/bVWY3C1Jrx7pJ7hAJZZK.jpg"]'::jsonb,
      'Imported from RentHub listing #40700 near Rangsit University. Approx. 56 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      14.0038522,
      100.5990069,
      27,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Pool","Fitness","Water Heater","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-main-gate',
      56,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000046787'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Home Inn Apartment Donmuang',
      'Don Mueang, Don Mueang, Bangkok',
      5500,
      4.9,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201812/20181220/bDPorqJDtB57cnxW5wf2.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201812/20181220/bDPorqJDtB57cnxW5wf2.jpg"]'::jsonb,
      'Imported from RentHub listing #46787 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      14.0111105,
      100.6118494,
      27,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-design',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000051592'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Klong 1 Mansion',
      'Thanyaburi, Pathumthani',
      2700,
      4.6,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201911/20191104/yCS5iXRjDun9UyBLpoxA.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201911/20191104/yCS5iXRjDun9UyBLpoxA.jpg"]'::jsonb,
      'Imported from RentHub listing #51592 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9260284,
      100.6084423,
      23,
      1,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000069111'::uuid,
      demo_owner_id,
      rsu_university_id,
      'ARAM HAUS Near Rangsit University 100 m.',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      11200,
      4.4,
      'LUXURY',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202504/20250408/9HwGnY5qtD2GyaQVjMUr.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202504/20250408/9HwGnY5qtD2GyaQVjMUr.jpg"]'::jsonb,
      'Imported from RentHub listing #69111 near Rangsit University. Approx. 6 minutes to campus context. Address document verified on source platform.',
      13.9685398,
      100.5904642,
      37,
      2,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Lift","Convenience Shop","Water Heater","Refrigerator","Fingerprint Access"]'::jsonb,
      'rsu-design',
      6,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":500,"serviceFee":250}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000065485'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Forest Oak',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      12000,
      4.4,
      'LUXURY',
      'condo',
      'https://bcdn.renthub.in.th/listing_picture/202305/20230501/CreRQcyAfuG8Ne4ybGRo.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202305/20230501/CreRQcyAfuG8Ne4ybGRo.jpg"]'::jsonb,
      'Imported from RentHub listing #65485 near Rangsit University. Approx. 15 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9739956,
      100.5935166,
      38,
      2,
      1,
      1,
      true,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Fitness","Water Heater","Refrigerator","Keycard Access","Fingerprint Access"]'::jsonb,
      'rsu-library',
      15,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":0,"serviceFee":250}'::jsonb,
      true,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000054475'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Cozy.S Residence',
      'Don Mueang, Don Mueang, Bangkok',
      5850,
      4.3,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202005/20200515/G9HiGYTTRCCniPXDczK7.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202005/20200515/G9HiGYTTRCCniPXDczK7.jpg"]'::jsonb,
      'Imported from RentHub listing #54475 near Rangsit University. Approx. 50 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9409668,
      100.5601198,
      28,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-design',
      50,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000027990'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Prima Residence **Ready to move in**',
      'Don Mueang, Don Mueang, Bangkok',
      6700,
      4.6,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201710/20171009/yKfQSmmeR7E2h4SoDGk6.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201710/20171009/yKfQSmmeR7E2h4SoDGk6.jpg"]'::jsonb,
      'Imported from RentHub listing #27990 near Rangsit University. Approx. 60 minutes to campus context. Address document verified on source platform.',
      13.9659041,
      100.6426825,
      29,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Fitness","Water Heater","Keycard Access"]'::jsonb,
      'rsu-engineering',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000010600'::uuid,
      demo_owner_id,
      rsu_university_id,
      'The Enrich Rungsit',
      'Prachathipat, Thanyaburi, Pathumthani',
      4150,
      4.4,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201510/20151001/DhoWkn7uzcMyBbqaBvZV.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201510/20151001/DhoWkn7uzcMyBbqaBvZV.jpg"]'::jsonb,
      'Imported from RentHub listing #10600 near Rangsit University. Approx. 44 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9827617,
      100.5613176,
      25,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Laundry","Water Heater","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      44,
      '["songthaew-muang-ake","rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000069534'::uuid,
      demo_owner_id,
      rsu_university_id,
      'New room with furniture & appliances, Rangsit-Tiwanon area, on main road.',
      'Bang Kadi, Muang Pathum Thani, Pathumthani',
      9300,
      4.5,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202507/20250703/UNUnyraqjhsqPEUyYrQr.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202507/20250703/UNUnyraqjhsqPEUyYrQr.jpg"]'::jsonb,
      'Imported from RentHub listing #69534 near Rangsit University. Approx. 57 minutes to campus context. Address document verified on source platform.',
      13.945237,
      100.5508338,
      34,
      2,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Lift","Pool","Fitness","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-engineering',
      57,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":500,"serviceFee":250}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000016208'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Rangsit Grand Condo',
      'Khlong Nung, Khlong Luang, Pathumthani',
      5700,
      4.5,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202508/20250830/ipYFs3dNQVDHfuq4PDnL.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202508/20250830/ipYFs3dNQVDHfuq4PDnL.jpg"]'::jsonb,
      'Imported from RentHub listing #16208 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      14.0063095,
      100.5628293,
      28,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000042715'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Nattawan Place',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      4250,
      4.3,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202302/20230216/WULCtqU82gJUaGfZs3uy.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202302/20230216/WULCtqU82gJUaGfZs3uy.jpg"]'::jsonb,
      'Imported from RentHub listing #42715 near Rangsit University. Approx. 9 minutes to campus context. Address document verified on source platform.',
      13.9631558,
      100.5814398,
      25,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Water Heater","Fingerprint Access","Pet Friendly"]'::jsonb,
      'rsu-design',
      9,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":250,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000047590'::uuid,
      demo_owner_id,
      rsu_university_id,
      '3DiamondPlace Apartment',
      'Prachathipat, Thanyaburi, Pathumthani',
      7250,
      4.6,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201901/20190130/9uzBxB4HExSvj9hEqy7x.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201901/20190130/9uzBxB4HExSvj9hEqy7x.jpg"]'::jsonb,
      'Imported from RentHub listing #47590 near Rangsit University. Approx. 35 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9716978,
      100.562913,
      30,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Lift","Fitness","Water Heater","Refrigerator","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-engineering',
      35,
      '["songthaew-muang-ake","rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000014603'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Rungsaeng Apartment Rangsit',
      'Prachathipat, Thanyaburi, Pathumthani',
      2850,
      4.3,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201506/20150629/xLLdACJXxF5SgkBHB1ZD.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201506/20150629/xLLdACJXxF5SgkBHB1ZD.jpg"]'::jsonb,
      'Imported from RentHub listing #14603 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9920767,
      100.5536146,
      23,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Keycard Access"]'::jsonb,
      'rsu-design',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000032949'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Baan Klong Nueng',
      'Prachathipat, Thanyaburi, Pathumthani',
      3500,
      4.2,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201612/20161212/Zkekqr6b4HPrzc51zhPq.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201612/20161212/Zkekqr6b4HPrzc51zhPq.jpg"]'::jsonb,
      'Imported from RentHub listing #32949 near Rangsit University. Approx. 60 minutes to campus context. Address document verified on source platform.',
      13.9252429,
      100.6103661,
      24,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Keycard Access"]'::jsonb,
      'rsu-library',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000005788'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Chuchoke Apartment',
      'Prachathipat, Thanyaburi, Pathumthani',
      3450,
      4.8,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201412/20141204/1d8bVkrp86xqTYXf36bz.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201412/20141204/1d8bVkrp86xqTYXf36bz.jpg"]'::jsonb,
      'Imported from RentHub listing #5788 near Rangsit University. Approx. 59 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9837169,
      100.5485743,
      24,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Lift","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      59,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000067137'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Serene Room',
      'Don Mueang, Don Mueang, Bangkok',
      9700,
      4.2,
      'CONDO',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202401/20240126/Bngp8f7E4NAShCwCMVvT.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202401/20240126/Bngp8f7E4NAShCwCMVvT.jpg"]'::jsonb,
      'Imported from RentHub listing #67137 near Rangsit University. Approx. 57 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9983757,
      100.6115931,
      34,
      2,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Fitness","Convenience Shop","Water Heater","Refrigerator","TV","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-library',
      57,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":0,"serviceFee":250}'::jsonb,
      true,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000069524'::uuid,
      demo_owner_id,
      rsu_university_id,
      'New room with furniture and appliances, near Rangsit University and Red Line train.',
      'Bang Phun, Muang Pathum Thani, Pathumthani',
      11300,
      4.2,
      'LUXURY',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202507/20250702/tHYCLJz2cuzPVxD3XD5T.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202507/20250702/tHYCLJz2cuzPVxD3XD5T.jpg"]'::jsonb,
      'Imported from RentHub listing #69524 near Rangsit University. Approx. 18 minutes to campus context. Address document verified on source platform.',
      13.9724907,
      100.5771096,
      37,
      2,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Security","CCTV","Parking","Lift","Pool","Fitness","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      18,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":500,"serviceFee":250}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000055375'::uuid,
      demo_owner_id,
      rsu_university_id,
      'The Link  Songprapa',
      'Don Mueang, Don Mueang, Bangkok',
      5650,
      4.7,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202006/20200624/1X5MML9TKzn68XdoGFvi.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202006/20200624/1X5MML9TKzn68XdoGFvi.jpg"]'::jsonb,
      'Imported from RentHub listing #55375 near Rangsit University. Approx. 60 minutes to campus context.',
      13.9296163,
      100.6127884,
      27,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-design',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000055667'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Three-D Residence',
      'Don Mueang, Don Mueang, Bangkok',
      5500,
      4.5,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202007/20200722/oTgy7dXmSzBjkS82bXk8.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202007/20200722/oTgy7dXmSzBjkS82bXk8.jpg"]'::jsonb,
      'Imported from RentHub listing #55667 near Rangsit University. Approx. 60 minutes to campus context. Virtual tour available on source listing.',
      14.0132187,
      100.5675174,
      27,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-design',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000010148'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Naleenplace Apartment',
      'Khu Khot, Lam Luk Ka, Pathumthani',
      3800,
      4.7,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202401/20240131/1iKgxz6dZGKTXVBmzGQG.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202401/20240131/1iKgxz6dZGKTXVBmzGQG.jpg"]'::jsonb,
      'Imported from RentHub listing #10148 near Rangsit University. Approx. 31 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9721259,
      100.6096525,
      24,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Laundry","Lift","Convenience Shop","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      31,
      '["songthaew-muang-ake","rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000065377'::uuid,
      demo_owner_id,
      rsu_university_id,
      'THE EMPIRE APARTMENT',
      'Bang Kadi, Muang Pathum Thani, Pathumthani',
      4800,
      4.6,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202303/20230317/zKVj4afN6X9Mh8vPxuh2.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202303/20230317/zKVj4afN6X9Mh8vPxuh2.jpg"]'::jsonb,
      'Imported from RentHub listing #65377 near Rangsit University. Approx. 55 minutes to campus context.',
      13.9851026,
      100.5524808,
      26,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-library',
      55,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000030010'::uuid,
      demo_owner_id,
      rsu_university_id,
      'MONO Placee',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      5750,
      4.3,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201812/20181201/3t1F6AKt6GvUSBYgRb3g.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201812/20181201/3t1F6AKt6GvUSBYgRb3g.jpg"]'::jsonb,
      'Imported from RentHub listing #30010 near Rangsit University. Approx. 14 minutes to campus context.',
      13.9692637,
      100.578192,
      28,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Water Heater","Pet Friendly"]'::jsonb,
      'rsu-engineering',
      14,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000018618'::uuid,
      demo_owner_id,
      rsu_university_id,
      'N. C. Residence',
      'Prachathipat, Thanyaburi, Pathumthani',
      4500,
      4.7,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/201711/20171116/oZjeGGzX3dHafiZ2ERd9.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201711/20171116/oZjeGGzX3dHafiZ2ERd9.jpg"]'::jsonb,
      'Imported from RentHub listing #18618 near Rangsit University. Approx. 59 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9244472,
      100.599797,
      26,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Fitness","Keycard Access"]'::jsonb,
      'rsu-engineering',
      59,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000065637'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Leelawadee',
      'Prachathipat, Thanyaburi, Pathumthani',
      3550,
      4.7,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202408/20240822/LRXCeD25GQDMYbnYdjfN.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202408/20240822/LRXCeD25GQDMYbnYdjfN.jpg"]'::jsonb,
      'Imported from RentHub listing #65637 near Rangsit University. Approx. 60 minutes to campus context. Address document verified on source platform.',
      13.9918448,
      100.6241104,
      24,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Convenience Shop","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-library',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000050034'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Jusco Mansion Don Mueang',
      'Si Khan, Don Mueang, Bangkok',
      2800,
      4.7,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202604/20260403/ue5WkcKeTdAjHK4kCdy6.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202604/20260403/ue5WkcKeTdAjHK4kCdy6.jpg"]'::jsonb,
      'Imported from RentHub listing #50034 near Rangsit University. Approx. 57 minutes to campus context.',
      13.9475081,
      100.6257614,
      23,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","CCTV","Parking","Laundry","Keycard Access"]'::jsonb,
      'rsu-engineering',
      57,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":250,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000047433'::uuid,
      demo_owner_id,
      rsu_university_id,
      'KMD Mansion',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      4500,
      4.3,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202104/20210429/yEfgN9huMbcocTP3Enga.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202104/20210429/yEfgN9huMbcocTP3Enga.jpg"]'::jsonb,
      'Imported from RentHub listing #47433 near Rangsit University. Approx. 5 minutes to campus context. Address document verified on source platform.',
      13.9665741,
      100.5844091,
      26,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Lift","Water Heater","Keycard Access"]'::jsonb,
      'rsu-library',
      5,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000041966'::uuid,
      demo_owner_id,
      rsu_university_id,
      'LETTER PARK APARTMENT',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      4500,
      4.3,
      'DORM',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202111/20211129/Y47pHnxVUNWfPw64aacv.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202111/20211129/Y47pHnxVUNWfPw64aacv.jpg"]'::jsonb,
      'Imported from RentHub listing #41966 near Rangsit University. Approx. 14 minutes to campus context. Address document verified on source platform.',
      13.9570577,
      100.5808423,
      26,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Pool","Fitness","Convenience Shop","Water Heater","Keycard Access"]'::jsonb,
      'rsu-engineering',
      14,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000014593'::uuid,
      demo_owner_id,
      rsu_university_id,
      'ELISE',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      6500,
      4.7,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201506/20150629/brD3W7YujMEdtY9AExtg.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201506/20150629/brD3W7YujMEdtY9AExtg.jpg"]'::jsonb,
      'Imported from RentHub listing #14593 near Rangsit University. Approx. 15 minutes to campus context. Virtual tour available on source listing. Address document verified on source platform.',
      13.9755312,
      100.590581,
      29,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Security","CCTV","Parking","Laundry","Lift","Pool","Fitness","Convenience Shop","Water Heater","Refrigerator","TV","Keycard Access","Fingerprint Access"]'::jsonb,
      'rsu-library',
      15,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000062638'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Khlong 1 Place',
      'Prachathipat, Thanyaburi, Pathumthani',
      3300,
      4.4,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202203/20220330/Dn4EFmFjV8jY4RKqzu72.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202203/20220330/Dn4EFmFjV8jY4RKqzu72.jpg"]'::jsonb,
      'Imported from RentHub listing #62638 near Rangsit University. Approx. 60 minutes to campus context. Address document verified on source platform.',
      13.9293604,
      100.5497388,
      24,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Lift","Keycard Access"]'::jsonb,
      'rsu-engineering',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000068428'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Mst House',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      10750,
      4.5,
      'LUXURY',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/202601/20260131/Q81t2gNsu7NspQJP2HaU.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202601/20260131/Q81t2gNsu7NspQJP2HaU.jpg"]'::jsonb,
      'Imported from RentHub listing #68428 near Rangsit University. Approx. 10 minutes to campus context. Address document verified on source platform.',
      13.966541,
      100.59538,
      36,
      2,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Convenience Shop","Water Heater","Refrigerator","TV","Keycard Access"]'::jsonb,
      'rsu-main-gate',
      10,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":20,"internetFee":0,"serviceFee":250}'::jsonb,
      true,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000070364'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Take A Rest Donmuang Residence)',
      'Don Mueang, Don Mueang, Bangkok',
      4500,
      4.2,
      'DORM',
      'shared',
      'https://bcdn.renthub.in.th/listing_picture/202511/20251120/LgjcqHvn6CqhoBhhihDq.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202511/20251120/LgjcqHvn6CqhoBhhihDq.jpg"]'::jsonb,
      'Imported from RentHub listing #70364 near Rangsit University. Approx. 60 minutes to campus context.',
      13.9500707,
      100.5380916,
      26,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","Parking"]'::jsonb,
      'rsu-main-gate',
      60,
      '["rsu-shuttle-green"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000030361'::uuid,
      demo_owner_id,
      rsu_university_id,
      '@Dorm',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      5500,
      4.4,
      'DORM',
      'apartment',
      'https://bcdn.renthub.in.th/listing_picture/201609/20160927/mnetgDHSz48Uu3Ff5pNZ.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/201609/20160927/mnetgDHSz48Uu3Ff5pNZ.jpg"]'::jsonb,
      'Imported from RentHub listing #30361 near Rangsit University. Approx. 13 minutes to campus context.',
      13.9718689,
      100.5818567,
      27,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Water Heater","Refrigerator","TV","Fingerprint Access"]'::jsonb,
      'rsu-library',
      13,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":7,"waterPerUnit":18,"internetFee":0,"serviceFee":180}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    ),
(
      '00000000-0000-0000-0000-000000025620'::uuid,
      demo_owner_id,
      rsu_university_id,
      'Campus Women Dormitory',
      'Lak Hok, Muang Pathum Thani, Pathumthani',
      3000,
      4.2,
      'BUDGET',
      'dorm',
      'https://bcdn.renthub.in.th/listing_picture/202204/20220401/yxBBmUeiq6UbmkHA49hU.jpg',
      '["https://bcdn.renthub.in.th/listing_picture/202204/20220401/yxBBmUeiq6UbmkHA49hU.jpg"]'::jsonb,
      'Imported from RentHub listing #25620 near Rangsit University. Approx. 5 minutes to campus context.',
      13.9681304,
      100.5875064,
      23,
      1,
      1,
      1,
      false,
      'active',
      'approved',
      '["Air Conditioning","Furniture","Internet","CCTV","Parking","Laundry","Water Heater","Keycard Access","Pet Friendly"]'::jsonb,
      'rsu-main-gate',
      5,
      '["songthaew-muang-ake"]'::jsonb,
      '{"electricityPerUnit":6,"waterPerUnit":16,"internetFee":0,"serviceFee":120}'::jsonb,
      false,
      '[{"months":1,"label":"Short Stay"},{"months":4,"label":"Semester"},{"months":6,"label":"Half-Year"},{"months":12,"label":"Annual"}]'::jsonb,
      now(),
      null
    )
  on conflict (id) do update
    set owner_user_id = coalesce(excluded.owner_user_id, listings.owner_user_id),
        university_id = excluded.university_id,
        title = excluded.title,
        location = excluded.location,
        price = excluded.price,
        rating = excluded.rating,
        category = excluded.category,
        room_type = excluded.room_type,
        image = excluded.image,
        gallery = excluded.gallery,
        description = excluded.description,
        latitude = excluded.latitude,
        longitude = excluded.longitude,
        area_sqm = excluded.area_sqm,
        capacity = excluded.capacity,
        bedrooms = excluded.bedrooms,
        bathrooms = excluded.bathrooms,
        featured = excluded.featured,
        listing_status = excluded.listing_status,
        moderation_status = excluded.moderation_status,
        amenities = excluded.amenities,
        nearest_campus_zone_id = excluded.nearest_campus_zone_id,
        walking_minutes = excluded.walking_minutes,
        transport_route_ids = excluded.transport_route_ids,
        utility_rates = excluded.utility_rates,
        internet_included = excluded.internet_included,
        lease_options = excluded.lease_options,
        available_from = excluded.available_from,
        available_to = excluded.available_to;
end
$$;
